title: DeadTrap
description: A proof that no phone number is untraceable
author: Chr0m0s0m3s
nav:
  - Social: 
    - type: 'Discord'
      Username: 'Som#5254'
    - type: 'Steam'
      link: 'https://steamcommunity.com/id/chr0m0s0m3s'
theme: jekyll-theme-dinky
